server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    proxy_intercept_errors on;

    error_page 502 503 504 /50x.html;

    location /portrait/ {
        proxy_pass http://backend:8000/portrait/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /50x.html {
        internal;
    }
}