# Generated by Django 5.2.7 on 2026-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicperformances',
            fields=[
                ('perf_id', models.AutoField(primary_key=True, serialize=False)),
                ('perf_year', models.CharField(max_length=16)),
                ('perf_current', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perf_digital', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perf_main', models.IntegerField(blank=True, null=True)),
                ('perf_first_retake', models.IntegerField(blank=True, null=True)),
                ('perf_second_retake', models.IntegerField(blank=True, null=True)),
                ('perf_grade_retake', models.IntegerField(blank=True, null=True)),
                ('perf_final', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academicperformances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courseresults',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_an_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_client_focus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_communication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_leadership', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_result_orientation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_planning_org', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_rules_culture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_self_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_collaboration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_stress_resistance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_emotions_communication', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_negotiations', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_digital_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_effective_learning', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_entrepreneurship', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_creativity_tech', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_trendwatching', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_conflict_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_career_management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_burnout', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_cross_cultural_comm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course_mentoring', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'courseresults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], default='running', max_length=16)),
                ('disciplines_found', models.IntegerField(default=0)),
                ('disciplines_saved', models.IntegerField(default=0)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Лог парсинга учебного плана',
                'verbose_name_plural': 'Логи парсинга учебного плана',
                'db_table': 'curriculumparselog',
                'ordering': ['-started_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datauploadtemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=256, unique=True)),
                ('template_description', models.TextField(blank=True, null=True)),
                ('template_config', models.JSONField()),
                ('template_created_at', models.DateTimeField(blank=True, null=True)),
                ('template_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datauploadtemplate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplineCompetencyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_name', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Название дисциплины')),
                ('rsv_competencies', models.JSONField(default=list, verbose_name='РСВ-компетенции (res_comp_*)')),
                ('standard_competencies', models.JSONField(default=list, verbose_name='Стандартные компетенции ФГОС')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('parsed_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего парсинга')),
            ],
            options={
                'verbose_name': 'Маппинг дисциплин → компетенции',
                'verbose_name_plural': 'Маппинг дисциплин → компетенции',
                'db_table': 'disciplinecompetencymapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationdisciplines',
            fields=[
                ('edu_disc_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_disc_name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'educationdisciplines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationforms',
            fields=[
                ('edu_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_form_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'educationforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educationspecialties',
            fields=[
                ('edu_spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_spec_name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'educationspecialties',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Academicperformance',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='PortraitUploadtemplate',
        ),
    ]
