# Generated by Django 5.2.7 on 2026-09-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portrait', '0002_academicperformances_courseresults_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseresults',
            table='Courseresults',
        ),
    ]
